[env]
# DB_URL = "postgres://postgres:postgres@localhost:5432/gator?sslmode=disable"

[hooks]
enter = "mise i -q"
[tools]
go = "latest"
"go:github.com/bootdotdev/bootdev" = "latest"
"go:github.com/pressly/goose/v3/cmd/goose" = "latest"
"go:github.com/sqlc-dev/sqlc/cmd/sqlc" = "latest"

[tasks."build"]
description = "Build the app"
run = "go build ."

[tasks."boom"]
depends = ["migrate:down"]
depends_post = ["migrate:up"]

[tasks."migrate:up"]
run = "goose postgres {{env.DB_URL}} up"
dir = "{{cwd}}/sql/schema"

[tasks."migrate:down"]
run = "goose postgres {{env.DB_URL}} down"
dir = "{{cwd}}/sql/schema"

[tasks."generate:sql"]
run = "sqlc generate"
dir = "{{cwd}}"
alias = "gs"
