[tools]
go = "latest"
"go:github.com/bootdotdev/bootdev" = "latest"
"go:github.com/pressly/goose/v3/cmd/goose" = "latest"
"go:github.com/sqlc-dev/sqlc/cmd/sqlc" = "latest"

[tasks]
run = "go run ."
test = "go test ./..."
build = "go build"
